"""Add user_configs table

Revision ID: c1c21ee5d1e1
Revises: 0001
Create Date: 2026-04-02 18:07:46.386185
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c1c21ee5d1e1'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('encrypted_key', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_configs_user_id'), 'user_configs', ['user_id'], unique=False)
    op.drop_index(op.f('file_embeddings_embedding_idx'), table_name='file_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # Recreate the IVFFlat index (autogenerate dropped it because it was created via raw SQL in 0001)
    op.execute(
        "CREATE INDEX IF NOT EXISTS file_embeddings_embedding_idx ON file_embeddings USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)"
    )
    op.drop_constraint(op.f('file_embeddings_file_id_fkey'), 'file_embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'file_embeddings', 'uploaded_files', ['file_id'], ['id'])
    op.alter_column('uploaded_files', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uploaded_files', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'file_embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('file_embeddings_file_id_fkey'), 'file_embeddings', 'uploaded_files', ['file_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('file_embeddings_embedding_idx'), 'file_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_user_configs_user_id'), table_name='user_configs')
    op.drop_table('user_configs')
    # ### end Alembic commands ###
